name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to manually trigger this workflow from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner provided by GitHub Actions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out the repository
      # This action checks out your repository code so that it can be accessed during the workflow.
      - name: Check out the code
        uses: actions/checkout@v4

      # Step 2: Set up JDK 11
      # Most Android builds require Java, so this step sets up the required JDK version.
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # Use Zulu distribution of Java
          java-version: '11'    # Specify the Java version

      # Step 3: Cache Gradle dependencies
      # Caches Gradle dependencies to speed up subsequent builds.
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches # Directory to cache
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Step 4: Set up Android SDK
      # This step installs the Android SDK necessary for building the Android app.
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 31       # Specify the Android API level
          build-tools: 31.0.0 # Specify the build-tools version
          target: default     # Target the default emulator image
          ndk: false          # Disable NDK (Native Development Kit) unless required

      # Step 5: Build the Android app
      # Runs the Gradle build task to compile your Android app.
      - name: Build the app
        run: ./gradlew assembleDebug

      # Step 6: Run tests
      # Executes unit tests and instrumented tests defined in your Android project.
      - name: Run unit tests
        run: ./gradlew test
